In [ ]:
#Assignment: Introduction to NumPy
# Objective
# The purpose of this assignment is to help students understand the basics of NumPy, including creating
# arrays, performing mathematical operations, and manipulating data efficiently.

In [ ]:
# Part 1 — Beginner Level
# Task 1: Install and Import NumPy
# 1. Install NumPy using pip.
# 2. Import NumPy in Python using the standard alias.

In [2]:
# pip install numpy
import numpy as np

In [13]:
# Task 2: Create NumPy Arrays
# Create the following arrays:
# 1. A 1D array containing numbers from 1 to 10
# 2. A 2D array of 3 rows and 3 columns
# 3. An array filled with zeros (5 elements)
# 4. An array filled with ones (5 elements)

In [14]:
oneDarray = np.arange(1,11)

twoDarray = np.arange(9)
newTwoDarray = twoDarray.reshape(3,3)

zerroArray = np.zeros(5)

onesArray = np.ones(5)

print(oneDarray)
print(newTwoDarray)
print(zerroArray)
print(onesArray)

[ 1  2  3  4  5  6  7  8  9 10]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]


In [18]:
# Task 3: Basic Array Operations
"""
Using two arrays:
A = [1,2,3,4,5]
B = [5,4,3,2,1]
Perform:
1. Addition
2. Subtraction
3. Multiplication
4. Division
"""
A = np.array([1,2,3,4,5])
B = np.array([5,4,3,2,1])
addition = A + B
subtraction = A - B
multiplication = A * B
division = A / B

print(addition)
print(subtraction)
print(multiplication)
print(division)



[6 6 6 6 6]
[-4 -2  0  2  4]
[5 8 9 8 5]
[0.2 0.5 1.  2.  5. ]


In [32]:
# Task 4: Array Information
"""
Create an array of numbers 1–20 and display:
1. Shape of the array
2. Total number of elements
3. Data type of the array
"""

arrayNum = np.arange(1,21)
newArrayNum = arrayNum.reshape(4,5)
print(newArrayNum)
print(arrayNum.shape)
print(arrayNum.size)
print(type(newArrayNum))
print(newArrayNum.dtype)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
(20,)
20
<class 'numpy.ndarray'>
int64


In [3]:
# Task 5: Indexing
"""
Create the following array:
[10,20,30,40,50,60,70]
Print:
1. First element
2. Last element
3. Elements from index 2 to 5
"""
ar = np.array([10,20,30,40,50,60,70])

print(ar[0])
print(ar[-1])
print(ar[2:5])

10
70
[30 40 50]


In [26]:
# Part 2 — Intermediate Level
"""
Task 6: Random Arrays
Create a 4x4 random array using NumPy.
Print:
1. Minimum value
2. Maximum value
3. Mean (average)
4. Sum of all elements
"""

import random as rd
randomFour = np.random.randint(0,30,(4,4))
print(randomFour)

print(randomFour.min())
print(randomFour.max())
print(randomFour.mean())
print(randomFour.sum())

[[ 2 14 10 11]
 [13  8  2 21]
 [11  0 24 12]
 [23 21  3 14]]
0
24
11.8125
189


In [32]:
# Task 7: Reshaping Arrays
"""
Create an array from 1–12.
1. Reshape it into 3 rows and 4 columns
2. Reshape it into 4 rows and 3 columns
Print both results.
"""
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newArr = arr.reshape(3,4)
newArr2 = arr.reshape(4,3)
print(f"3 rows and 4 columns:\n {newArr}")
print("======")
print(f"4 rows 3 columns:\n {newArr2}")

3 rows and 4 columns:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
4 rows 3 columns:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [40]:
# Task 8: Matrix Operations
"""
Create two matrices:
A = [[1,2,3],
[4,5,6]]
B = [[7,8,9],
[1,2,3]]
Perform:
1. Matrix addition
2. Matrix subtraction
3. Element-wise multiplication
"""

A = [[1,2,3],
     [4,5,6]]

B = [[7,8,9],
     [1,2,3]]

add = np.add(A,B)
print(f"Matrix addition: \n{add}")
sub = np.subtract(A,B)
print(f"Matrix Subtraction: \n{sub}")
mul = np.multiply(A,B)
print(f"Element-wise multiplication: \n{mul}")


Matrix addition: 
[[ 8 10 12]
 [ 5  7  9]]
Matrix Subtraction: 
[[-6 -6 -6]
 [ 3  3  3]]
Element-wise multiplication: 
[[ 7 16 27]
 [ 4 10 18]]


In [52]:
# Task 9: Filtering Data
"""
Create an array of numbers 1–30.
Print only the numbers that are:
1. Greater than 15
2. Even numbers
"""
arr = np.arange(1,31)
newAr = arr.reshape((5,6))
print(newAr)

greater = arr[arr >15]

print(f"Greater than 15: \n{greater}")

even = arr[arr%2==0]
print(f"Even numbers: \n{even}")

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]
Greater than 15: 
[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]
Even numbers: 
[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30]


In [60]:
# Task 10: Practical Problem
"""
Create an array representing marks of 10 students.
Tasks:
1. Find the highest marks
2. Find the lowest marks
3. Calculate the average marks
4. Display students who scored above average
"""
studentMarks = np.random.randint(33,99,(1,11))
print(studentMarks)

highestMark = np.max(studentMarks)

print(highestMark)

lowestMark = np.min(studentMarks)

print(lowestMark)

averageMarks = np.mean(studentMarks)
print(averageMarks)

aboveAvg = studentMarks[studentMarks > averageMarks]
print(aboveAvg)

[[58 68 86 67 58 66 43 79 82 88 69]]
88
43
69.45454545454545
[86 79 82 88]
