In [2]:
from numpy.ma.core import size

"""==== Section #1 ====="""
# 1. The print() Function
# Focus: String manipulation and formatting.
# 1. The Multi-Line Story: Print a short story (3 lines) using only one print() statement

multi = input("Enter Line1: ")
line = input("Enter Line2: ")
story = input("Enter Line3: ")

print(f" {multi}\n" f" {line}\n" f" {story}")

 This is
 The Short
 Story Multiple line.


In [ ]:
#2. The Border: Print the word "PYTHON" surrounded by a box made of asterisks (*).

In [13]:
#3. The Separator: Use the sep parameter to print the numbers 1 through 5 separated by arrows (e.g., 1 -> 2 -> 3).
numbers = input("Enter numbers 1 to 5: ")
sep = input("Enter sep: ")
print(*numbers, sep=f"{sep}")

1->2->3->4->5


In [ ]:
#4. The End Game: Print two separate sentences on the same line using the end parameter.

In [ ]:
#5. The Formatter: Print a decimal number (like 12.34567) rounded to exactly two decimal places using an f-string.

In [15]:
"""==== Section #2 ====="""
#2. The input() Function
#Focus: Type casting and user interaction.
#1. The Greeter: Ask for a name and a favorite color, then print: "Hi [Name], [Color] looks great on you!"
name = input("Enter Name: ")
fav_color = input("Enter Favorite Color: ")
print(f"Hi {name}, {fav_color} Color looks great on you!")

Hi Ahsan, Black Color looks great on you!


In [16]:
#2. The Age Gap: Ask for the user's age and print how old they will be in the year 2050
age = int(input("Enter Age: "))
current_year = int(input("Enter Current Year: "))
future_Year = int(input("Enter Future Year to calculate your Age: "))
print(f"You are {age+(future_Year - current_year)} years old in {future_Year}.")

You are 2099 years old in 4100.


In [17]:
#3. The Multiplier: Ask for two numbers, multiply them, and print the result. (Watch out for string vs. integer errors!)
num1 = int(input("Enter First Number: "))
num2 = int(input("Enter Second Number: "))
multiply = num1 * num2
print(f"Multiply {num1} by {num2} = {multiply}")

Multiply 45 by 4 = 180


In [18]:
#4. The Repeater: Ask for a word and a number, then print that word as many times as the number specifies.
word = str(input("Enter Word: "))
num = int(input("Enter Number: "))
print((word+"\n")*num)

Ahsan
Ahsan
Ahsan
Ahsan
Ahsan
Ahsan



In [22]:
#5. The Bill Splitter: Ask for a total bill amount and the number of people. Print how much each person owes.
total_bill = int(input("Enter Total Bill: "))
num_people = int(input("Enter Number of People: "))
splitt = total_bill / num_people
print(int(splitt))

42


In [85]:
"""==== Section #3 ====="""
#Focus: Arithmetic logic and remainders.
#1. The Remainder: Ask for two numbers and print only the remainder when the first is divided by the second.
remNum1 = int(input("Enter Number1: "))
remNum2 = int(input("Enter Number2: "))
print(f"the Number1: {remNum1} and Number2: {remNum2} = Remainder: {remNum1 % remNum2}")

the Number1: 5 and Number2: 7 = Remainder: 5


In [91]:
#2. The Power: Write a program that calculates $x^y$ where $x$ and $y$ are user inputs.
x = int(input("Enter X value: "))
y = int(input("Enter Y value: "))
calculate = x**y
print(f"Calculate {x} ^ {y} = {calculate}")

Calculate 4 ^ 3 = 64


In [99]:
#3. The Floor: Perform "floor division" on two numbers and explain why the result is an integer.
oneNum = int(input("Enter One Number: "))
twoNum = int(input("Enter Two Number: "))
flrDivi = oneNum // twoNum
print(f"One Number: {oneNum} // TwoNumber: {twoNum} = {flrDivi} floor division rounded down the {oneNum/twoNum} to nearest whole number")

One Number: 9 // TwoNumber: 2 = 4 floor division rounded down the 4.5 to nearest whole number


In [106]:
#4. The Comparison: Ask for a number and print True if it is greater than 100 and False otherwise (without using an if statement).
userInpNum = int(input("Enter Number: "))
print(userInpNum > 100)

True


In [110]:
#5. The Swapper: Use operators to swap the values of two variables $a$ and $b$ without using a third temporary variable.
a = input("value1: ")
b = input("value2: ")
print(f"Before a: {a},  and b: {b} ")
a,b = b, a
print(f"After a: {a},  and b: {b} ")

Before a: this is A,  and b: this is B 
After a: this is B,  and b: this is A 


In [111]:
"""==== Section #4 ====="""
#Focus: Naming conventions and reassignment.
#1. The Scoreboard: Create a variable score starting at 0. Update it by 10, then decrease it by 3, and print the final value.
scoreStart = 0
scoreStart +=10
scoreStart -=3
print(f"Final value of score: {scoreStart}")

Final value of score: 7


In [114]:
#2. The Constant: Create a variable for PI (3.14159) and calculate the area of a circle based on a user-provided radius.
piVar = 3.14159
radius = int(input("Enter Radius: "))
Area = piVar*radius**2
print(Area)

201.06176


In [115]:
#3. The Concatenator: Store a first name and a last name in different variables, then combine them into a full_name variable.
firstName = str(input("Enter First Name: "))
lastName = str(input("Enter Last Name: "))
full_name = firstName + " " + lastName
print(full_name)

Ahsan Khan


In [116]:
#4. The Type Checker: Create three variables (a string, an integer, and a float) and print the type() of each.
var1 = "string"
var2 = 5
var3 = 7.9
print(type(var1),type(var2),type(var3))

<class 'str'> <class 'int'> <class 'float'>


In [121]:
#5. The Dynamic Type: Assign a number to a variable, print it, then assign a string to that same variable and print it again.
varNum = 5
print(type(varNum))
varNum = "String"
print(type(varNum))

<class 'int'>
<class 'str'>


In [123]:
"""==== Section #5 ====="""
#5. IF / ELSE
#Focus: Conditional logic and branching.
#1. Odd or Even: Ask for a number and tell the user if it is even or odd.
num = int(input("Enter Number: "))
if num%2==0:
    print("the number is even")
else:
    print("the number is odd")

the number is odd


In [133]:
#2. The Grade Book: Take a score (0-100) and print "A" for 90+, "B" for 80+, and "F" for anything below 60.
score = int(input("Enter Score(0-100): "))
if 90 <= score <= 100:
    print("Grade: A")
elif 80 <= score < 90:
    print("Grade: B")
elif 60 <= score < 80:
    print("Grade: Passing")
elif 0 <= score < 60:
    print("Grade: F")
else:
    print("Invalid Score Please enter score 0 to 100.")

Grade: A


In [137]:
#3. The Bouncer: Ask for a user's age. If they are 18 or older, say "Enter"; otherwise, tell them how many years they have to wait.
age = int(input("Enter Age: "))
if age >= 18:
    print("Enter")
else:
    yearWait = 18 - age
    print(f" no entry, you have to wait {yearWait}")

 no entry, you have to wait -42


In [140]:
#4. The Password: Create a "secret password" variable. Ask the user for input; if it matches, print "Access Granted."
secret_password = "AdvancedPython123"
userInputPass =  input("Enter Password")
if userInputPass == secret_password:
    print("Access granted")
else:
    print("Wrong password")

Access granted


In [146]:
#5. Leap Year: Ask for a year and determine if it is a leap year (divisible by 4 but not 100,unless divisible by 400).
year = int(input("Enter a year: "))
if(year%400 == 0):
    print(f"{year} is a Leap Year.")
elif(year%100 == 0):
    print(f"{year} is NOT a Leap Year.")
elif(year%4 == 0):
    print(f"{year} is a Leap Year.")
else:
    print(f"{year} is NOT a Leap Year.")

2028 is a Leap Year.


In [2]:
"""==== Section #6 ====="""
#Loops
#Focus: Iteration and termination
#1. The Countdown: Use a while loop to count down from 10 to 1 and then print "Blast off!"
countDown = 10
while countDown > 0:
    print(countDown)
    countDown -= 1
print("Blast off")


10
9
8
7
6
5
4
3
2
1
Blast off


In [7]:
#2. The Multiples: Use a for loop to print the first 10 multiples of 5.
for i in range(1,11):
    multiples = i*5
    print(f" 5x{i} = {multiples}")

 5x1 = 5
 5x2 = 10
 5x3 = 15
 5x4 = 20
 5x5 = 25
 5x6 = 30
 5x7 = 35
 5x8 = 40
 5x9 = 45
 5x10 = 50


In [15]:
#3. The Accumulator: Write a loop that asks the user for numbers until they type "0", then print the total sum of all numbers entered.
sumAllNum = 0
while True:
    userInpNum = int(input("Enter Number: "))
    if userInpNum == 0:
        break
    sumAllNum += userInpNum
print(f"Total Sum is {sumAllNum}")

Total Sum is 72


In [18]:
#4. The Searcher: Loop through a string and count how many times the letter "a" appears.
inpString = str(input("Enter Your String: "))
count = 0
for letter in inpString:
    if letter.lower()=="a":
        count +=1
print(inpString)
print(f"The letter a appears {count} times in the string.")

Apple banana Airplane
The letter a appears 6 times in the string.


In [19]:
#5. The Breakout: Write an infinite loop that only stops (break) when the user types the word "stop".
while True:
    userStrInp = str(input(""))
    if userStrInp.lower() == "stop":
        print("Break")
        break
    print(f"{userStrInp}")

this
is the
infinite 
loop
until
i use
a
word
Break


In [ ]:
"""==== Section #7 ====="""
#Data Structures (Lists/Tuples/Dicts)
#Focus: Storage and retrieval.
#1. The Grocery List: Create a list of 5 items. Replace the second item with "Milk" and remove the last item.

In [ ]:
#2. The Slicer: Given a list of 10 numbers, print only the middle four numbers using slicing.

In [ ]:
#3. The Dictionary: Create a dictionary of a "Phone Book" with 3 names and numbers. Print only the phone number of a specific name.

In [ ]:
#4. The Unique List: Given a list with duplicate numbers, create a new list (or set) that contains only the unique values.

In [ ]:
#5. The Coordinator: Create a tuple representing coordinates $(x, y)$. Try to change the $x$ value and explain why Python throws an error.

In [66]:
"""==== Section #8 ====="""
#NumPy (Multidimensional & Indexing)
#Focus: Array shapes and accessing data.
#1. The Matrix: Create a $3 \times 3$ NumPy array containing the numbers 1 through 9.
import numpy as np
threeByThree = np.array(range(9))
new_matrix = threeByThree.reshape(3,3)
print(new_matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [71]:
#2. The Corner: From a $4 \times 4$ array, use indexing to extract the value in the top-right corner.
fourByFour = np.array(range(16))
n_matrix = fourByFour.reshape(4,4)
print(n_matrix)
print("==========")
print(n_matrix[0:2,2:])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[2 3]
 [6 7]]


In [55]:
#3. The Row Picker: Create a $5 \times 5$ array of random numbers and print only the 3rd row.
fiveByFive = np.array(range(25))
ranNumArr = np.random.randint(1,10, size=(5, 5))
print(ranNumArr)
print("=========")
print(ranNumArr[2])


[[6 5 1 3 6]
 [1 6 9 7 2]
 [6 9 1 6 5]
 [3 7 5 9 8]
 [1 9 2 2 1]]
[6 9 1 6 5]


In [70]:
#4. The Sub-Grid: From a $6 \times 6$ array, extract a $2 \times 2$ "sub-matrix" from the center.
sixBySix = np.array(range(36))
s_matrix = sixBySix.reshape(6,6)
print(s_matrix)
print("==========")
print(s_matrix[2:4,2:4])

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
[[14 15]
 [20 21]]


In [80]:
#5. The Zero-Out: Create a $3 \times 3$ identity matrix (1s on the diagonal) and use indexing to change the center value to 10.
thrByThr = np.identity(3)
print(thrByThr)
print("=======")
thrByThr[1,1]=10
print(thrByThr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[ 1.  0.  0.]
 [ 0. 10.  0.]
 [ 0.  0.  1.]]
